---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]
  - name: windows-2012R2
    driver:
      box: mwrock/Windows2012R2
      guest: windows
      communicator: winrm
      gui: false

suites:
  - name: default
    require_chef_omnibus: 12.5.1
    run_list:
      - recipe[topbeat::default]
    attributes:
      topbeat:
        config:
          output:
            elasticsearch:
              hosts: ["127.0.0.1:9200"]
